app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


//Route::post('/payments/order', function () {
//    return 'Hello World';
//});


Route::group(['namespace' => 'Payments', 'prefix' => 'payments'], function () {
    Route::resource('order', 'AvisoController');
    Route::resource('status', 'StatusController');
});


/**
 * Авторизация, регистрация, востановление пароля
 */
Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);
Route::resource('language', 'Language\LanguageController');

/**
 * Администратор
 */
Route::group(['namespace' => 'Dashboard', 'middleware' => ['auth', 'admin'], 'prefix' => 'dashboard'], function () {

    Route::resource('user', 'UserController');
    Route::resource('editor', 'EditorUserController');
    Route::resource('page', 'PageController');
    Route::resource('news', 'NewsController');
    Route::resource('shares', 'SharesController');
    Route::resource('', 'AdminController');
    //Route::resource('feedback', 'FeedbackController');
    Route::resource('category', 'CategoryController');
    Route::resource('goods', 'GoodsController');
    Route::resource('order', 'OrderController');
    Route::resource('comments', 'CommentsController');
    Route::resource('filemanager', 'FileManagerController');
    Route::resource('review', 'ReviewController');
    Route::resource('task', 'TaskController');
    Route::resource('langorder', OrderLangController::class);
    Route::resource('block', 'BlockController');
    Route::resource('element', 'ElementController');

    Route::resource('statinfo', 'StatInfoController');

    Route::resource('benefits', BenefitsController::class);


    Route::get('/wmenuindex', array('as' => 'wmenuindex', 'uses' => 'WmenuController@wmenuindex'));
    Route::post('/addcustommenu', array('as' => 'addcustommenu', 'uses' => 'WmenuController@addcustommenu'));
    Route::post('/deleteitemmenu', array('as' => 'deleteitemmenu', 'uses' => 'WmenuController@deleteitemmenu'));
    Route::post('/deletemenug', array('as' => 'deletemenug', 'uses' => 'WmenuController@deletemenug'));
    Route::post('/createnewmenu', array('as' => 'createnewmenu', 'uses' => 'WmenuController@createnewmenu'));
    Route::post('/generatemenucontrol', array('as' => 'generatemenucontrol', 'uses' => 'WmenuController@generatemenucontrol'));
    Route::post('/updateitem', array('as' => 'updateitem', 'uses' => 'WmenuController@updateitem'));
});


Route::group(['namespace' => 'Site'], function () {
    Route::resource('', 'IndexController');
    Route::resource('page', 'PageController');
    Route::resource('news', 'NewsController');
    Route::resource('feedback', 'FeedbackController');
    Route::resource('review', 'ReviewController');
    Route::resource('search', 'SearchController');
    Route::resource('catalog', 'CatalogController');


    Route::group(['middleware' => ['auth', 'user']], function () {
        Route::resource('home', 'HomeController');
        //  Route::resource('setting', 'SettingController');
        Route::resource('order', 'OrderController');
        Route::resource('comments', 'CommentsController');
        Route::resource('payments', 'PaymentsController');
        Route::resource('filemanager', 'FileManagerController');
    });
});


Route::group(['middleware' => ['auth'], 'namespace' => 'Site'], function () {

    Route::resource('setting', 'SettingController');
});


Route::group(['namespace' => 'Editor', 'middleware' => ['auth', 'editor'], 'prefix' => 'editor'], function () {
    Route::resource('', 'IndexController');
    Route::resource('order', 'OrderController');
    Route::resource('chan', 'ChanController');
    Route::resource('comment', 'CommentController');
    Route::resource('filemanager', 'FileManagerController');

    Route::resource('payments', 'PaymentsController');
});

app/Http/Controllers/Dashboard/AdminController.php
<?php namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Feedback;
use App\Models\News;
use App\Models\Order;
use App\Models\Page;
use App\Models\Review;
use App\Models\Task;
use App\Models\User;
use Cache;
use DB;

class AdminController extends Controller
{


    public function index()
    {

        $Users = Cache::remember('Users', 10, function () {
            return User::where('type', 'users')->count();
        });

        $Editors = Cache::remember('Editors', 10, function () {
            return User::where('type', 'editor')->count();
        });

        $LastOrder = Cache::remember('LastOrder', 10, function () {
            return Order::orderBy('id', 'desc')->limit(5)->get();
        });

        $Pages = Cache::remember('Pages', 10, function () {
            return Page::count();
        });


        $News = Cache::remember('News', 10, function () {
            return News::count();
        });


        $Review = Cache::remember('Review', 10, function () {
            return Review::count();
        });


        $LastTask = Cache::remember('LastTask', 10, function () {
            return Task::orderBy('id', 'desc')->limit(5)->get();
        });


        $statOrderMath = Cache::remember('statOrderMath', 10, function () {
            return DB::table('order')
                ->select(DB::raw("DATE_FORMAT(`created_at`, '%d') as dat , COUNT('id') as count"))
                ->whereRaw("created_at >= DATE_SUB(CURRENT_DATE, INTERVAL 30 DAY) ")
                ->groupBy('dat')
                ->orderBy('dat', 'DESC')
                ->get();
        });


        $allOrder = Cache::remember('allOrder', 10, function () {
            return Order::count();
        });


        $completeOrder = Cache::remember('completeOrder', 10, function () {
            return Order::where('status', 'Готова')->count();
        });


        $dangerOrder = Cache::remember('dangerOrder', 10, function () {
            return Order::where('status', 'Отменён')->count();
        });

        $toWork = $allOrder - $completeOrder - $dangerOrder;


        $noRead = Cache::remember('$noRead', 10, function () {
            return Feedback::where('read', false)->count();
        });


        return view("dashboard/home", [
            'lastOrder' => $LastOrder,
            'users' => $Users,
            'editors' => $Editors,
            'pages' => $Pages,
            'news' => $News,
            'review' => $Review,
            "statOrderMath" => $statOrderMath,
            "allOrder" => $allOrder,
            "completeOrder" => $completeOrder,
            "dangerOrder" => $dangerOrder,
            "toWork" => $toWork,
            'noRead' => $noRead,
            'LastTask' => $LastTask,
        ]);
    }


}

app/Http/Controllers/Dashboard/BenefitsController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Task;
use Illuminate\Http\Request;


class BenefitsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Tasks = Task::where('payment', 0)
            ->sortable()
            ->where('status', 'Завершена')
            ->with('getUser')
            ->paginate(15);

        return view('dashboard.user.benefits', [
            'Tasks' => $Tasks
        ]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Task::findOrFail($id)->fill($request->all())->save();
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Dashboard/BlockController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Block;
use Illuminate\Http\Request;
use Session;

class BlockController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $Blocks = Block::paginate(15);

        return view('dashboard.block.index', [
            'Blocks' => $Blocks
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('dashboard.block.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        Block::create($request->all());
        Session::flash('good', 'Вы успешно создали блок');
        return redirect()->route('dashboard.block.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * @param $block
     * @return \Illuminate\View\View
     */
    public function edit($block)
    {
        return view("dashboard/block/edit", [
            'block' => $block
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request $request
     * @param  int $id
     * @return Response
     */
    public function update(Request $request, $block)
    {
        $block->fill($request->all());
        $block->save();
        Session::flash('good', 'Вы успешно изменили значения');
        return redirect()->route('dashboard.block.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($block)
    {
        $block->delete('cascade');
        Session::flash('good', 'Вы успешно удалили значения');
        return redirect()->route('dashboard.block.index');
    }
}

app/Http/Controllers/Dashboard/CategoryController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Request;
use Session;


class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $Category = Category::orderBy('id', 'desc')->paginate(15);
        return view("dashboard/category/category", ['Category' => $Category]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view("dashboard/category/create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request $request
     * @return Response
     */
    public function store(CategoryRequest $request)
    {

        $Category = new Category($request->all());
        $Category->save();

        //Флеш сообщение
        Session::flash('good', 'Вы успешно изменили значения');
        return redirect()->route('dashboard.category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit(Category $category)
    {
        return view("dashboard/category/edit", [
            'Category' => $category
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request $request
     * @param  int $id
     * @return Response
     */
    public function update(Category $Category, CategoryRequest $request)
    {

        $Category->fill($request->all());
        $Category->save();

        //Флеш сообщение
        Session::flash('good', 'Вы успешно изменили значения');
        return redirect()->route('dashboard.category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy(Category $category)
    {
        $category->delete('cascade');
        Session::flash('good', 'Вы успешно удалили значения');
        return redirect()->route('dashboard.category.index');
    }
}

app/Http/Controllers/Dashboard/CommentsController.php
<?php
namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Http\Requests\CommentsRequest;
use App\Models\Comments;
use Auth;
use Illuminate\Http\Request;
use Session;

class CommentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request $request
     * @return Response
     */
    public function store(CommentsRequest $request)
    {
        $comments = new Comments($request->all());
        $comments->user_id = Auth::user()->id;
        $comments->save();
        Session::flash('good', 'Вы успешно добавили комментарий');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request $request
     * @param  int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Dashboard/FileManagerController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Files;
use Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class FileManagerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        foreach ($request->file('files') as $file) {
            $file->move(storage_path() . '/app/order/', Str::ascii(time() . '-' . $file->getClientOriginalName()));
            $DBfile = new Files([
                'user_id' => Auth::user()->id,
                'original' => $file->getClientOriginalName(),
                'name' => Str::ascii(time() . '-' . $file->getClientOriginalName()),
                'type' => $request->input('type'),
                'beglouto' => $request->input('beglouto'),
                'finish' => true,
            ]);
            $DBfile->save();
        }

        return abort(200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        $file = Files::findOrFail($id);
        return response()->download(storage_path() . '/app/order/' . $file->name);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request $request
     * @param  int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/dashboard/block/create.blade.php
@extends('app')

@section('content')


    <div class="bg-light lter b-b wrapper-md">
        <h1 class="m-n font-thin h3"> Новый блок</h1>
    </div>
    <div class="wrapper-md">
        <form class="row" role="form" action="{{URL::route('dashboard.block.store')}}"
              method="post" class="row"
              enctype="multipart/form-data">
            <div class="col-sm-4">
                <div class="panel panel-default">
                    <div class="panel-heading font-bold">Общая информация</div>
                    <div class="panel-body">


                        <div class="form-group">
                            <label>Имя</label>
                            <input class="form-control" type="text" maxlength="255" required name="name"
                                   value="">
                        </div>

                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <button type="submit" class="btn btn-primary">Отправить</button>


                    </div>
                </div>
            </div>
        </form>
    </div>

@endsection

resources/views/dashboard/block/edit.blade.php
@extends('app')

@section('content')


    <div class="bg-light lter b-b wrapper-md">
        <h1 class="m-n font-thin h3"> {{ $block->name}}</h1>
    </div>
    <div class="wrapper-md">
        <form class="row" role="form" action="{{URL::route('dashboard.block.update',  $block->id)}}"
              method="post" class="row"
              enctype="multipart/form-data">
            <div class="col-sm-4">
                <div class="panel panel-default">
                    <div class="panel-heading font-bold">Общая информация</div>
                    <div class="panel-body">


                        <div class="form-group">
                            <label>Имя</label>
                            <input class="form-control" type="text" maxlength="255" required name="name"
                                   value="{{$block->name or ''}}">
                        </div>

                        <input type="hidden" name="_method" value="PUT">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <button type="submit" class="btn btn-primary">Отправить</button>


                    </div>
                </div>
            </div>
        </form>
    </div>

@endsection

resources/views/dashboard/block/index.blade.php
@extends('app')

@section('content')


    <div class="bg-light lter b-b wrapper-md">
        <h1 class="m-n font-thin h3"> Список блоков</h1>
    </div>
    <div class="wrapper-md">
        <div class="panel panel-default">
            <div class="panel-heading">

                <a href="{{URL::route('dashboard.block.create')}}" class="btn btn-link btn-sm"><span
                            class="fa fa-plus"></span> Добавить
                    новый блок </a>


            </div>
            <div class="table-responsive">
                <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table table-striped m-b-none dataTable no-footer" id="DataTables_Table_0"
                                   role="grid" aria-describedby="DataTables_Table_0_info">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Имя блока</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($Blocks as $block)
                                    <tr>
                                        <td>{{ $block->id }}</td>
                                        <td>{{ $block->name }}</td>
                                        <td class="pull-right">


                                            <a href="{{URL::route('dashboard.element.show', $block->id)}}"
                                               class="btn btn-success"><span class="fa fa-cube"></span> </a>

                                            <a href="{{URL::route('dashboard.block.edit', $block->id)}}"
                                               class="btn btn-primary"><span class="fa fa-edit"></span> </a>

                                            <form action="{{URL::route('dashboard.block.destroy',$block->id)}}"
                                                  method="post" class="pull-right">
                                                <input type="hidden" name="_method" value="delete">
                                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                <button type="submit" class="btn btn-danger"><span
                                                            class="fa fa-trash-o"></span></button>
                                            </form>


                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-sm-6 text-center">
                            <small class="text-muted inline m-t-sm m-b-sm">Всего
                                элементов: {!! $Blocks->count() !!}</small>
                        </div>
                        <div class="col-sm-6 text-right text-center-xs">
                            {!! $Blocks->render() !!}
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>



@endsection