app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


//Route::post('/payments/order', function () {
//    return 'Hello World';
//});


Route::group(['namespace' => 'Payments', 'prefix' => 'payments'], function () {
    Route::resource('order', 'AvisoController');
    Route::resource('status', 'StatusController');
});


/**
 * Авторизация, регистрация, востановление пароля
 */
Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);
Route::resource('language', 'Language\LanguageController');

/**
 * Администратор
 */
Route::group(['namespace' => 'Dashboard', 'middleware' => ['auth', 'admin'], 'prefix' => 'dashboard'], function () {

    Route::resource('user', 'UserController');
    Route::resource('editor', 'EditorUserController');
    Route::resource('page', 'PageController');
    Route::resource('news', 'NewsController');
    Route::resource('shares', 'SharesController');
    Route::resource('', 'AdminController');
    //Route::resource('feedback', 'FeedbackController');
    Route::resource('category', 'CategoryController');
    Route::resource('goods', 'GoodsController');
    Route::resource('order', 'OrderController');
    Route::resource('comments', 'CommentsController');
    Route::resource('filemanager', 'FileManagerController');
    Route::resource('review', 'ReviewController');
    Route::resource('task', 'TaskController');
    Route::resource('langorder', OrderLangController::class);
    Route::resource('block', 'BlockController');
    Route::resource('element', 'ElementController');

    Route::resource('statinfo', 'StatInfoController');

    Route::resource('benefits', BenefitsController::class);


    Route::get('/wmenuindex', array('as' => 'wmenuindex', 'uses' => 'WmenuController@wmenuindex'));
    Route::post('/addcustommenu', array('as' => 'addcustommenu', 'uses' => 'WmenuController@addcustommenu'));
    Route::post('/deleteitemmenu', array('as' => 'deleteitemmenu', 'uses' => 'WmenuController@deleteitemmenu'));
    Route::post('/deletemenug', array('as' => 'deletemenug', 'uses' => 'WmenuController@deletemenug'));
    Route::post('/createnewmenu', array('as' => 'createnewmenu', 'uses' => 'WmenuController@createnewmenu'));
    Route::post('/generatemenucontrol', array('as' => 'generatemenucontrol', 'uses' => 'WmenuController@generatemenucontrol'));
    Route::post('/updateitem', array('as' => 'updateitem', 'uses' => 'WmenuController@updateitem'));
});


Route::group(['namespace' => 'Site'], function () {
    Route::resource('', 'IndexController');
    Route::resource('page', 'PageController');
    Route::resource('news', 'NewsController');
    Route::resource('feedback', 'FeedbackController');
    Route::resource('review', 'ReviewController');
    Route::resource('search', 'SearchController');
    Route::resource('catalog', 'CatalogController');


    Route::group(['middleware' => ['auth', 'user']], function () {
        Route::resource('home', 'HomeController');
        //  Route::resource('setting', 'SettingController');
        Route::resource('order', 'OrderController');
        Route::resource('comments', 'CommentsController');
        Route::resource('payments', 'PaymentsController');
        Route::resource('filemanager', 'FileManagerController');
    });
});


Route::group(['middleware' => ['auth'], 'namespace' => 'Site'], function () {

    Route::resource('setting', 'SettingController');
});


Route::group(['namespace' => 'Editor', 'middleware' => ['auth', 'editor'], 'prefix' => 'editor'], function () {
    Route::resource('', 'IndexController');
    Route::resource('order', 'OrderController');
    Route::resource('chan', 'ChanController');
    Route::resource('comment', 'CommentController');
    Route::resource('filemanager', 'FileManagerController');

    Route::resource('payments', 'PaymentsController');
});

app/Http/Controllers/Editor/ChanController.php
<?php

namespace App\Http\Controllers\Editor;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Http\Requests\Editor\ChanRequest;
use App\Models\Task;
use Auth;
use Illuminate\Http\Request;
use Session;


class ChanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {

        $freeTask = Task::where('user_id', 0)->with('getGoods')->paginate(15);
        return view('editor.chan', [
            'Tasks' => $freeTask,
        ]);


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request $request
     * @return Response
     */
    public function store(ChanRequest $request)
    {
        $task = Task::where('user_id', 0)->findOrFail($request->task_id);
        $task->user_id = Auth::user()->id;
        $task->status = "В работе";
        $task->save();

        //event(new Notification($task->id));

        Session::flash('good', trans('alert.You have successfully taken the task'));
        return redirect()->back();

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request $request
     * @param  int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Editor/CommentController.php
<?php

namespace App\Http\Controllers\Editor;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Comments;
use Auth;
use Illuminate\Http\Request;
use Session;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        $task = Auth::user()->getTask()->findOrFail($request->beglouto);
        $comments = new Comments([
            'beglouto' => $task->id,
            'type' => 'task',
            'user_id' => Auth::user()->id,
            'text' => $request->text,
        ]);
        $comments->save();
        Session::flash('good', trans('alert.You have successfully added a comment'));
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request $request
     * @param  int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Editor/CommentsController.php
<?php

namespace App\Http\Controllers\Editor;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Comments;
use Auth;
use Illuminate\Http\Request;
use Session;

class CommentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        $comments = new Comments($request->all());
        $comments->user_id = Auth::user()->id;
        $comments->type = "task";
        $comments->save();
        Session::flash('good', trans('alert.You have successfully added a comment'));
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request $request
     * @param  int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Editor/FileManagerController.php
<?php

namespace App\Http\Controllers\Editor;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Files;
use App\Models\FilesMeta;
use Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Session;
use Storage;


class FileManagerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        foreach ($request->file('files') as $file) {

            if (!is_null($file)) {
                $task = Auth::user()->getTask()->findOrFail($request->beglouto);


                if (!Storage::exists('/app/order/' . date("Y-m-d"))) {
                    Storage::makeDirectory('/app/order/' . date("Y-m-d"));
                }

                $file->move(storage_path() . '/app/order/' . date("Y-m-d"), Str::ascii(time() . '-' . $file->getClientOriginalName()));
                $DBfile = new Files([
                    'user_id' => Auth::user()->id,
                    'original' => $file->getClientOriginalName(),
                    'name' => date("Y-m-d") . '/' . Str::ascii(time() . '-' . $file->getClientOriginalName()),
                    'type' => 'task',
                    'beglouto' => $task->id,
                    'finish' => true,
                ]);
                $DBfile->save();

                $DBMeta = new FilesMeta([
                    'files_id' => $DBfile->id,
                    'user_id' => Auth::user()->id,
                    'task_id' => $task->id,
                ]);
                $DBMeta->save();
            }

        }

        Session::flash('good', trans('trans.You have successfully added a comment'));
        return redirect()->back();

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request $request
     * @param  int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Editor/IndexController.php
<?php

namespace App\Http\Controllers\Editor;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use Illuminate\Http\Request;

class IndexController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        return redirect('/editor/chan');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request $request
     * @param  int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Editor/OrderController.php
<?php

namespace App\Http\Controllers\Editor;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Comments;
use Auth;
use Illuminate\Http\Request;
use Session;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $Tasks = Auth::user()->getTask()->where('status', '!=', 'Завершена')->orderBy('id', 'Desc')->paginate(15);
        return view('editor.order', [
            'Tasks' => $Tasks
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($task)
    {
        $task = Auth::user()->getTask()->with('getGoods', 'getOrder', 'GetFileMeta.getFiles')->findOrFail($task);
        $comments = Comments::whereRaw('type = ? and beglouto = ?', ['task', $task->id])->get();
        return view('editor.task', [
            'Task' => $task,
            'Comments' => $comments
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request $request
     * @param  int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $task = Auth::user()->getTask()->findOrFail($id);
        $task->status = "На проверке";


        if ($task->spent == 0) {
            $task->spent = time() - $task->created_at->timestamp;
            $task->pause = date("Y-m-d H:i:s");
        } else {
            $task->spent = $task->spend + time() - $task->pause->timestamp;
            $task->pause = date("Y-m-d H:i:s");
        }


        $task->save();
        Session::flash('good', trans('alert.You have successfully changed the status of the task'));
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/editor/chan.blade.php
@extends('_layout/editor')

@section('content-editor')






    <div class="panel panel-default">
        <div class="panel-heading">{{trans('chan.Feed Task')}}</div>
        <table class="table">

            <thead>
            <tr>
                <th>{{trans('chan.Job title')}}</th>
                <th>{{trans('chan.Service')}}</th>
                <th>{{trans('chan.Price')}}</th>
                <th>{{trans('chan.Workload')}}</th>
                <th>{{trans('chan.Deadline')}}</th>
                <th>{{trans('chan.Control')}}</th>
            </tr>
            </thead>


            <tbody>
            @foreach($Tasks as $task)


                <tr>
                    <td>{{$task->name}}</td>

                    @if(App::getLocale() == 'ru')
                        <td>{{$task->getGoods->name}}</td>
                    @else
                        <td>{{$task->getGoods->eng_name}}</td>
                    @endif


                    <td>{{$task->price}} USD</td>
                    <td>{{$task->countWork}}</td>
                    <td>{{$task->workfinish}}</td>


                    <td>

                        <form action="{{route('editor.chan.store')}}" method="POST">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <input type="hidden" value="{{$task->id}}" name="task_id">
                            <button class="btn btn-link">{{trans('chan.Take')}}</button>
                        </form>
                    </td>


                </tr>
            @endforeach

            </tbody>


        </table>
    </div>


    {!! $Tasks->render()!!}












@endsection

resources/views/editor/index.blade.php
@extends('_layout/editor')

@section('content-editor')



@endsection

resources/views/editor/task.blade.php
@extends('_layout/editor')




@section('content-editor')


    <script type="text/javascript">
        function delElem(elem) {
            //Удаляем элемент (файл)
            $(elem).parent().remove();

        }
    </script>

    <div class="panel panel-default">
        <div class="panel-heading">{{trans('orderTask.Task')}} № {{$Task->id}}


            <form class="pull-right" action="{{route('editor.order.update',$Task->id)}}" method="post">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="finish" value="true">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <button class="btn btn-default  btn-xs">
                    {{trans('orderTask.End Task')}}
                </button>
            </form>


        </div>

        <div class="panel-body">

            <h4>{{$Task->name}}</h4>


            <hr>
            <p>{{trans('orderTask.Service')}}:</p>

            <ul class="list-group">
                <li class="list-group-item">
                    @if(App::getLocale() == 'ru')
                        {{$Task->getGoods->name}}
                    @else
                        {{$Task->getGoods->eng_name}}
                    @endif
                </li>
            </ul>
        </div>


        <ul class="list-group">
            <li class="list-group-item">{{trans('orderTask.Status')}}: <p
                        class="pull-right"> {{trans('status.'. $Task->status)}}</p></li>
            <li class="list-group-item">{{trans('orderTask.Deadline')}}: <p
                        class="pull-right">{{$Task->workfinish->tz(Config::get('app.timezone'))}}</p>
            </li>
            <li class="list-group-item">{{trans('orderTask.Price')}}: <p class="pull-right">{{$Task->price}} USD</p>
            </li>
        </ul>


        <ul id="myTabs" class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#comments" role="tab" data-toggle="tab" aria-controls="home"
                                                      aria-expanded="true">{{trans('orderTask.Comments')}}</a></li>
            <li role="presentation" class=""><a href="#oldfile" role="tab" data-toggle="tab" aria-controls="profile"
                                                aria-expanded="false">{{trans('orderTask.Available files')}}</a></li>
            <li role="presentation" class=""><a href="#newfile" role="tab" data-toggle="tab" aria-controls="profile"
                                                aria-expanded="false">{{trans('orderTask.Ready files')}}</a></li>
        </ul>
        <div id="myTabContent" class="tab-content">
            <div role="tabpanel" class="tab-pane fade active in" id="comments" aria-labelledby="home-tab">


                <div class="user-comment">
                    @foreach($Comments as $comment)
                        <p>{{$comment->text}}</p>
                        <p class="text-muted pull-right">{{$comment->created_at->tz(Config::get('app.timezone'))}}</p>
                        <hr>
                    @endforeach


                    <form action="{{URL::route('editor.comment.store')}}" method="post">
                        <div class="form-group">
                            <label>{{trans('orderTask.Write a comment')}}</label>
        <textarea class="form-control" rows="3" required name="text"
                  style="resize: none;"></textarea>
                        </div>
                        <input type="hidden" name="type" value="order">
                        <input type="hidden" name="beglouto" value="{{$Task->id}}">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <button type="submit" class="btn btn-primary btn-block">{{trans('orderTask.Send')}}</button>

                    </form>
                </div>


            </div>
            <div role="tabpanel" class="tab-pane fade" id="oldfile" aria-labelledby="profile-tab">


                <ul class="list-group">
                    <ul class="list-group">
                        @foreach($Task->getFileMeta as $file)
                            @if(!$file->getFiles->finish)
                                <a href="{{URL::route('filemanager.show', $file->getFiles->id)}}"
                                   class="list-group-item"><i
                                            class="fa fa-file-o"></i> {{$file->getFiles->original}}
                                    <small class="pull-right">{{$file->getFiles->created_at->tz(Config::get('app.timezone'))}}</small>
                                </a>
                            @endif
                        @endforeach
                    </ul>
                </ul>


            </div>
            <div role="tabpanel" class="tab-pane fade" id="newfile" aria-labelledby="profile-tab">
                <ul class="list-group">
                    <ul class="list-group">
                        @foreach($Task->getFileMeta as $file)
                            @if($file->getFiles->finish)
                                <a href="{{URL::route('filemanager.show', $file->getFiles->id)}}"
                                   class="list-group-item"><i
                                            class="fa fa-file-o"></i> {{$file->getFiles->original}}
                                    <small class="pull-right">{{$file->getFiles->created_at->tz(Config::get('app.timezone'))}}</small>
                                </a>
                            @endif
                        @endforeach
                    </ul>
                </ul>


                <div class="container-fluid">
                    <div class="row">
                        <form action="{{route('editor.filemanager.store')}}" method="post" class="text-center"
                              enctype="multipart/form-data">

                            <h6>{{trans('orderTask.Download the required documents')}}</h6>


                            <div class="fileinput fileinput-new input-group" data-provides="fileinput">
                                <div class="form-control" data-trigger="fileinput"><i
                                            class="glyphicon glyphicon-file fileinput-exists"></i> <span
                                            class="fileinput-filename"></span></div>
                                <span class="input-group-addon btn btn-default btn-file"><span
                                            class="fileinput-new">{{trans('file.Select file')}}</span><span
                                            class="fileinput-exists">{{trans('file.Change')}}</span><input type="file"
                                                                                                           name="files[]"></span>
                                <a href="#" class="input-group-addon btn btn-default fileinput-exists"
                                   data-dismiss="fileinput">{{trans('file.Remove')}}</a>
                            </div>


                            <div id="NewUploader">

                            </div>


                            <hr>
                            <a class="btn btn-link" id="MoreUpload">{{trans('file.More')}}</a>
                            <hr>


                            <input type="hidden" name="type" value="order">
                            <input type="hidden" name="beglouto" value="{{$Task->id}}">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <button class="btn btn-primary btn-block" type="submit">{{trans('orderTask.Send')}}!
                            </button>

                        </form>
                    </div>
                </div>


            </div>
        </div>


        <div class="panel-footer">
            <div class="text-center">
                <div class="clock-time"></div>
            </div>
        </div>

    </div>






    <script>
        window.onload = function () {


            $(document).ready(function () {


                var myhtml = '<div class="fileinput fileinput-new input-group" data-provides="fileinput">';
                myhtml += '<div class="form-control" data-trigger="fileinput"><i class="glyphicon glyphicon-file fileinput-exists"></i> <span class="fileinput-filename"></span></div>';
                myhtml += '<span class="input-group-addon btn btn-default btn-file"><span class="fileinput-new">{{trans("file.Select file")}}</span><span class="fileinput-exists">{{trans("file.Change")}}</span><input type="file" name="files[]"></span>';
                myhtml += ' <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">{{trans("file.Remove")}}</a>';
                myhtml += '</div>';

                $("#MoreUpload").click(function () {
                    $("#NewUploader").html(
                            $("#NewUploader").html() + myhtml
                    );
                });


                var clock = $('.clock-time').FlipClock(
                        @if(strtotime($Task->workfinish->tz(Config::get('app.timezone'))) - time() < 0)
                            {{0}}
                        @else
                             {{strtotime($Task->workfinish->tz(Config::get('app.timezone'))) - time()}}
                        @endif

                        , {
                            'autoStart': true,
                            'countdown': true,
                            'clockFace': 'DailyCounter'
                        });


                //Проверка состояния загрузки файлов
                $("#fileselect").on('click', function () {
                    var obj = $("#messages");

                    //Если юзер берет файлы то очищаем те которые он уже залил
                    $('li', obj).each(function () {
                        $(this).remove();
                    });

                    //Количество файлов, хз зачем я это сделал
                    //var countFiles = this.files.length;

                });

                $('.nextBtn').click(function () {
                    var checket = $(".order input[type='radio']:checked").val();
                    if (checket == 6) {
                        $('#izdanie').removeClass('hidden');
                    }
                    else {
                        $('#izdanie').addClass('hidden');
                    }
                });


                var navListItems = $('div.setup-panel div a'),
                        allWells = $('.setup-content'),
                        allNextBtn = $('.nextBtn');

                allWells.hide();

                navListItems.click(function (e) {
                    e.preventDefault();
                    var $target = $($(this).attr('href')),
                            $item = $(this);

                    if (!$item.hasClass('disabled')) {
                        navListItems.removeClass('btn-primary').addClass('btn-default');
                        $item.addClass('btn-primary');
                        allWells.hide();
                        $target.show();
                        $target.find('input:eq(0)').focus();
                    }
                });

                allNextBtn.click(function () {
                    var curStep = $(this).closest(".setup-content"),
                            curStepBtn = curStep.attr("id"),
                            nextStepWizard = $('div.setup-panel div a[href="#' + curStepBtn + '"]').parent().next().children("a"),
                            curInputs = curStep.find("input[type='text'],input[type='url']"),
                            isValid = true;

                    $(".form-group").removeClass("has-error");
                    for (var i = 0; i < curInputs.length; i++) {
                        if (!curInputs[i].validity.valid) {
                            isValid = false;
                            $(curInputs[i]).closest(".form-group").addClass("has-error");
                        }
                    }

                    if (isValid)
                        nextStepWizard.removeAttr('disabled').trigger('click');
                });

                $('div.setup-panel div a.btn-primary').trigger('click');
            });


        };
    </script>








@endsection